// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diyqzfuuunrmxszmgxdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpeXF6ZnV1dW5ybXhzem1neGRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDU1NTYsImV4cCI6MjA2NDEyMTU1Nn0.j0Xc4QxL_L3M31XYagt9Y3iWanigkMbu5PbVKP2D5zU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);